"""new_migration

Revision ID: 208df640331b
Revises: 94f9848c80f8
Create Date: 2026-01-29 06:05:50.420324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208df640331b'
down_revision = '94f9848c80f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('mandatory_ack', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='newsstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employee.eid'], name=op.f('fk_news_author_id_employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    op.create_index(op.f('ix_news_author_id'), 'news', ['author_id'], unique=False)
    op.create_index(op.f('ix_news_is_pinned'), 'news', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('user_followed_categories',
    sa.Column('user_eid', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_user_followed_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_eid'], ['employee.eid'], name=op.f('fk_user_followed_categories_user_eid_employee')),
    sa.PrimaryKeyConstraint('user_eid', 'category_id', name=op.f('pk_user_followed_categories'))
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employee.eid'], name=op.f('fk_comments_author_id_employee')),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_comments_news_id_news'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_news_id'), 'comments', ['news_id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_table('news_likes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_news_likes_news_id_news'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['employee.eid'], name=op.f('fk_news_likes_user_id_employee')),
    sa.PrimaryKeyConstraint('user_id', 'news_id', name=op.f('pk_news_likes'))
    )
    op.create_table('news_tags',
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_news_tags_news_id_news'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_news_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'tag_id', name=op.f('pk_news_tags'))
    )
    op.create_table('news_to_category',
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_news_to_category_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_news_to_category_news_id_news'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'category_id', name=op.f('pk_news_to_category'))
    )
    op.create_table('news_to_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_news_to_files_file_id_file'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_news_to_files_news_id_news'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'news_id', 'file_id', name=op.f('pk_news_to_files'))
    )
    op.create_table('comments_likes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comments_likes_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['employee.eid'], name=op.f('fk_comments_likes_user_id_employee')),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name=op.f('pk_comments_likes'))
    )
    op.create_table('comments_to_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comments_to_files_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_comments_to_files_file_id_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'comment_id', 'file_id', name=op.f('pk_comments_to_files'))
    )
    op.create_table('mentions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('mentioned_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_mentions_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['employee.eid'], name=op.f('fk_mentions_mentioned_user_id_employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentions')
    op.drop_table('comments_to_files')
    op.drop_table('comments_likes')
    op.drop_table('news_to_files')
    op.drop_table('news_to_category')
    op.drop_table('news_tags')
    op.drop_table('news_likes')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_news_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('user_followed_categories')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_is_pinned'), table_name='news')
    op.drop_index(op.f('ix_news_author_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
