"""new_migration

Revision ID: 259907db67e8
Revises:
Create Date: 2025-11-19 02:32:22.488809

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "259907db67e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("eid", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(), nullable=False, comment="ФИО"),
        sa.Column(
            "position", sa.String(), nullable=False, comment="Должность"
        ),
        sa.Column(
            "department", sa.String(), nullable=False, comment="Подразделение"
        ),
        sa.Column(
            "birth_date", sa.Date(), nullable=False, comment="Дата рождения"
        ),
        sa.Column(
            "hire_date", sa.Date(), nullable=False, comment="Дата найма"
        ),
        sa.Column(
            "work_phone", sa.String(), nullable=True, comment="Рабочий телефон"
        ),
        sa.Column(
            "work_email",
            sa.String(),
            nullable=False,
            comment="Корпоративный email",
        ),
        sa.PrimaryKeyConstraint("eid", name=op.f("pk_employee")),
        sa.UniqueConstraint("work_email", name=op.f("uq_employee_work_email")),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file")),
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "employee_id",
            sa.BigInteger(),
            nullable=False,
            comment="Связь с таблицей Employee (EID)",
        ),
        sa.Column(
            "personal_phone",
            sa.String(),
            nullable=True,
            comment="Личный телефон",
        ),
        sa.Column("telegram", sa.String(), nullable=True, comment="Telegram"),
        sa.Column(
            "about_me", sa.String(), nullable=True, comment="О себе (текст)"
        ),
        sa.Column(
            "vacation_info",
            sa.String(),
            nullable=True,
            comment="Информация об отпуске",
        ),
        sa.Column(
            "avatar_id",
            sa.BigInteger(),
            nullable=True,
            comment="Файл с аватаром",
        ),
        sa.ForeignKeyConstraint(
            ["avatar_id"], ["file.id"], name=op.f("fk_profile_avatar_id_file")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.eid"],
            name=op.f("fk_profile_employee_id_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "employee_id", name=op.f("pk_profile")),
        sa.UniqueConstraint("telegram", name=op.f("uq_profile_telegram")),
    )
    op.create_table(
        "profile_project",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "profile_id", sa.BigInteger(), nullable=False, comment="Профиль"
        ),
        sa.Column(
            "name", sa.String(), nullable=True, comment="Название проекта"
        ),
        sa.Column(
            "start_d", sa.Date(), nullable=True, comment="Дата начала проекта"
        ),
        sa.Column(
            "end_d", sa.Date(), nullable=True, comment="Дата конца проекта"
        ),
        sa.Column(
            "position", sa.String(), nullable=True, comment="Роль в проекте"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
            name=op.f("fk_profile_project_profile_id_profile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_project")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_project")
    op.drop_table("profile")
    op.drop_table("file")
    op.drop_table("employee")
    # ### end Alembic commands ###
