"""new_migration

Revision ID: a72adacf8ae6
Revises:
Create Date: 2025-11-18 15:44:46.268502

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a72adacf8ae6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("eid", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(), nullable=False, comment="ФИО"),
        sa.Column(
            "position", sa.String(), nullable=False, comment="Должность"
        ),
        sa.Column(
            "department", sa.String(), nullable=False, comment="Подразделение"
        ),
        sa.Column(
            "birth_date", sa.Date(), nullable=False, comment="Дата рождения"
        ),
        sa.Column(
            "hire_date", sa.Date(), nullable=False, comment="Дата найма"
        ),
        sa.Column(
            "work_phone", sa.String(), nullable=True, comment="Рабочий телефон"
        ),
        sa.Column(
            "work_email",
            sa.String(),
            nullable=False,
            comment="Корпоративный email",
        ),
        sa.PrimaryKeyConstraint("eid", name=op.f("pk_employee")),
        sa.UniqueConstraint("work_email", name=op.f("uq_employee_work_email")),
    )
    op.create_table(
        "profile",
        sa.Column(
            "employee_id",
            sa.BigInteger(),
            nullable=False,
            comment="Связь с таблицей Employee (EID)",
        ),
        sa.Column(
            "avatar_url", sa.String(), nullable=True, comment="URL аватара"
        ),
        sa.Column(
            "personal_phone",
            sa.String(),
            nullable=True,
            comment="Личный телефон",
        ),
        sa.Column(
            "telegram_handle",
            sa.String(),
            nullable=True,
            comment="Telegram хендл",
        ),
        sa.Column(
            "about_me", sa.Text(), nullable=True, comment="О себе (текст)"
        ),
        sa.Column(
            "projects_list",
            sa.Text(),
            nullable=True,
            comment="Список проектов (например, JSON-массив)",
        ),
        sa.Column(
            "vacation_info",
            sa.Text(),
            nullable=True,
            comment="Информация об отпуске",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.eid"],
            name=op.f("fk_profile_employee_id_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("employee_id", name=op.f("pk_profile")),
        sa.UniqueConstraint(
            "telegram_handle", name=op.f("uq_profile_telegram_handle")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile")
    op.drop_table("employee")
    # ### end Alembic commands ###
