"""Add news and comment change logs

Revision ID: d4a1f3c2e5d8
Revises: c3a1f2b8d9e5
Create Date: 2026-02-16

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4a1f3c2e5d8'
down_revision = 'c3a1f2b8d9e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create news_change_log table
    op.create_table('news_change_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('news_id', sa.BigInteger(), nullable=False),
        sa.Column('changed_by_eid', sa.String(), nullable=False),
        sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('field_name', sa.String(), nullable=False),
        sa.Column('old_value', sa.String(), nullable=True),
        sa.Column('new_value', sa.String(), nullable=True),
        sa.Column('operation', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', name='profileoperationtype'), nullable=False),
        sa.ForeignKeyConstraint(['changed_by_eid'], ['employee.eid'], name=op.f('fk_news_change_log_changed_by_eid_employee'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_news_change_log_news_id_news'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_news_change_log'))
    )
    op.create_index(op.f('ix_news_change_log_news_id'), 'news_change_log', ['news_id'], unique=False)

    # Create comment_change_log table
    op.create_table('comment_change_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('comment_id', sa.BigInteger(), nullable=False),
        sa.Column('news_id', sa.BigInteger(), nullable=False),
        sa.Column('changed_by_eid', sa.String(), nullable=False),
        sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('field_name', sa.String(), nullable=False),
        sa.Column('old_value', sa.String(), nullable=True),
        sa.Column('new_value', sa.String(), nullable=True),
        sa.Column('operation', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', name='profileoperationtype'), nullable=False),
        sa.ForeignKeyConstraint(['changed_by_eid'], ['employee.eid'], name=op.f('fk_comment_change_log_changed_by_eid_employee'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_change_log_comment_id_comments'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_comment_change_log_news_id_news'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_change_log'))
    )
    op.create_index(op.f('ix_comment_change_log_comment_id'), 'comment_change_log', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_change_log_news_id'), 'comment_change_log', ['news_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_change_log_news_id'), table_name='comment_change_log')
    op.drop_index(op.f('ix_comment_change_log_comment_id'), table_name='comment_change_log')
    op.drop_table('comment_change_log')

    op.drop_index(op.f('ix_news_change_log_news_id'), table_name='news_change_log')
    op.drop_table('news_change_log')

    # ### end Alembic commands ###
