"""new_migration

Revision ID: e512fa917d49
Revises:
Create Date: 2025-11-19 12:16:59.592452

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e512fa917d49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Название подразделения",
        ),
        sa.Column(
            "parent_id",
            sa.BigInteger(),
            nullable=True,
            comment="Родительское подразделение (для иерархии)",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["department.id"],
            name=op.f("fk_department_parent_id_department"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file")),
    )
    op.create_table(
        "employee",
        sa.Column(
            "eid",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="EID/ID (read-only HR)",
        ),
        sa.Column(
            "full_name",
            sa.String(),
            nullable=False,
            comment="ФИО (read-only HR)",
        ),
        sa.Column(
            "position",
            sa.String(),
            nullable=False,
            comment="Должность (read-only HR)",
        ),
        sa.Column(
            "department_id",
            sa.BigInteger(),
            nullable=True,
            comment="Подразделение",
        ),
        sa.Column(
            "birth_date",
            sa.Date(),
            nullable=False,
            comment="Дата рождения (read-only HR)",
        ),
        sa.Column(
            "hire_date",
            sa.Date(),
            nullable=False,
            comment="Дата найма (read-only HR)",
        ),
        sa.Column(
            "work_phone",
            sa.String(),
            nullable=True,
            comment="Рабочий телефон (read-only HR)",
        ),
        sa.Column(
            "work_email",
            sa.String(),
            nullable=False,
            comment="Корпоративный email (read-only HR)",
        ),
        sa.Column(
            "work_band",
            sa.String(),
            nullable=True,
            comment="Band (read-only HR)",
        ),
        sa.Column(
            "manager_eid",
            sa.BigInteger(),
            nullable=True,
            comment="Руководитель (read-only HR)",
        ),
        sa.Column(
            "hrbp_eid",
            sa.BigInteger(),
            nullable=True,
            comment="HR-бизнес-партнёр (read-only HR)",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_employee_department_id_department"),
        ),
        sa.ForeignKeyConstraint(
            ["hrbp_eid"],
            ["employee.eid"],
            name=op.f("fk_employee_hrbp_eid_employee"),
        ),
        sa.ForeignKeyConstraint(
            ["manager_eid"],
            ["employee.eid"],
            name=op.f("fk_employee_manager_eid_employee"),
        ),
        sa.PrimaryKeyConstraint("eid", name=op.f("pk_employee")),
        sa.UniqueConstraint("work_email", name=op.f("uq_employee_work_email")),
    )
    op.create_table(
        "auth_token",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "employee_eid",
            sa.BigInteger(),
            nullable=False,
            comment="Связь с таблицей Employee (EID) - владелец токена",
        ),
        sa.Column(
            "token",
            sa.String(length=512),
            nullable=False,
            comment="Token или Session ID",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время истечения срока действия токена",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Время создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["employee_eid"],
            ["employee.eid"],
            name=op.f("fk_auth_token_employee_eid_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_token")),
        sa.UniqueConstraint(
            "employee_eid", name=op.f("uq_auth_token_employee_eid")
        ),
        sa.UniqueConstraint("token", name=op.f("uq_auth_token_token")),
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "employee_id",
            sa.BigInteger(),
            nullable=False,
            comment="Связь с таблицей Employee (EID)",
        ),
        sa.Column(
            "avatar_id",
            sa.BigInteger(),
            nullable=True,
            comment="Файл с аватаром (Редактируемый)",
        ),
        sa.Column(
            "personal_phone",
            sa.String(),
            nullable=True,
            comment="Личный телефон (Редактируемый)",
        ),
        sa.Column(
            "telegram",
            sa.String(),
            nullable=True,
            comment="Telegram (Редактируемый)",
        ),
        sa.Column(
            "about_me",
            sa.String(length=1000),
            nullable=True,
            comment="О себе (текст, до 1 000 символов, Редактируемый)",
        ),
        sa.ForeignKeyConstraint(
            ["avatar_id"], ["file.id"], name=op.f("fk_profile_avatar_id_file")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.eid"],
            name=op.f("fk_profile_employee_id_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
        sa.UniqueConstraint(
            "employee_id", name=op.f("uq_profile_employee_id")
        ),
    )
    op.create_table(
        "profile_project",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "profile_id", sa.BigInteger(), nullable=False, comment="Профиль"
        ),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Краткое название проекта (Редактируемый)",
        ),
        sa.Column(
            "start_d",
            sa.Date(),
            nullable=True,
            comment="Период: Дата начала проекта (Редактируемый)",
        ),
        sa.Column(
            "end_d",
            sa.Date(),
            nullable=True,
            comment="Период: Дата конца проекта (Редактируемый)",
        ),
        sa.Column(
            "position",
            sa.String(),
            nullable=True,
            comment="Роль в проекте (Редактируемый)",
        ),
        sa.Column(
            "link",
            sa.String(),
            nullable=True,
            comment="Ссылка (YouTrack/другое) (Редактируемый)",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
            name=op.f("fk_profile_project_profile_id_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_project")),
    )
    op.create_table(
        "profile_vacation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "profile_id",
            sa.BigInteger(),
            nullable=False,
            comment="Профиль сотрудника",
        ),
        sa.Column(
            "is_planned",
            sa.Boolean(),
            nullable=False,
            comment="Статус: True - планируется, False - текущий/завершенный",
        ),
        sa.Column(
            "start_date",
            sa.Date(),
            nullable=False,
            comment="Дата начала отпуска",
        ),
        sa.Column(
            "end_date", sa.Date(), nullable=False, comment="Дата конца отпуска"
        ),
        sa.Column(
            "substitute_eid",
            sa.BigInteger(),
            nullable=True,
            comment="Замещающий сотрудник",
        ),
        sa.Column(
            "comment",
            sa.String(),
            nullable=True,
            comment="Комментарий к отпуску (Редактируемый)",
        ),
        sa.Column(
            "is_official",
            sa.Boolean(),
            nullable=False,
            comment="Официальный статус из HR (read-only, контролирует фактический флаг 'в отпуске')",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
            name=op.f("fk_profile_vacation_profile_id_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["substitute_eid"],
            ["employee.eid"],
            name=op.f("fk_profile_vacation_substitute_eid_employee"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_vacation")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_vacation")
    op.drop_table("profile_project")
    op.drop_table("profile")
    op.drop_table("auth_token")
    op.drop_table("employee")
    op.drop_table("file")
    op.drop_table("department")
    # ### end Alembic commands ###
